add -T flag and better input checking

diff --git a/geco_trend_dump b/geco_trend_dump
--- a/geco_trend_dump
+++ b/geco_trend_dump
@@ -76,6 +76,14 @@ OPTIONS:
                           invocations of geco_trend_dump and will overwrite
                           existing files without complaint.
 
+    -T                    write dumped data to STDOUT instead of saving it to
+                          a file. Data is formatted the same way, and if
+                          multiple time segments are used for the dump, the
+                          output will contain multiple headers. This has the
+                          same effect as dumping the data to multiple files
+                          and then using e.g. \`cat\` to concatenate their
+                          content and print it to STDOUT.
+
     -h                    shows this message.
 
 EXAMPLES:
@@ -118,7 +126,6 @@ CHAN_TYPE='m-trend'           # Only use minute trends for now
 VALID_TREND_EXTENSIONS="mean min max n rms"
 NDS_SERVER='nds.ligo.caltech.edu'
 LOGFILE=/dev/stderr           # by default, just log to STDERR
-EPOCH_LENGTH=6000
 
 ##############################
 # HELPER FUNCTIONS
@@ -131,20 +138,33 @@ log () {
 }
 
 # get the path to the output directory based on channel name and path prefix
-get_outdir () {
-    local outdir_pre="${1}"
-    local channel_name="${2}"
-    # default output directory is ~/geco_trend_dump.d/channel_name;
-    # else is $outdir_pre/geco_trend_dump.d/channel_name
-    if [ "$outdir_pre" == "" ]; then
-        printf "$HOME/geco_trend_dump.d/$(
-            printf "${channel_name}" | tr ':' '_'
-        )"
+get_outfile () {
+    local gps_start_time="${1}"
+    local gps_end_time="${2}"
+    local channel_name="${3}"
+    local trend_extensions="${4}"
+    local outdir_pre="${5}"
+    # if -T flag specified, just print to STDOUT
+    if "${print_timeseries_to_stdout}"; then
+        local outfile="/dev/stdout"
     else
-        printf "${outdir_pre}/geco_trend_dump.d/$(
-            printf "${channel_name}" | tr ':' '_'
-        )"
+        # default output directory is ~/geco_trend_dump.d/channel_name;
+        # else is $outdir_pre/geco_trend_dump.d/channel_name
+        if [ "$outdir_pre" == "" ]; then
+            outdir="$HOME/geco_trend_dump.d/$(
+                printf "${channel_name}" | tr ':' '_'
+            )"
+        else
+            outdir="${outdir_pre}/geco_trend_dump.d/$(
+                printf "${channel_name}" | tr ':' '_'
+            )"
+        fi
+        # make sure output directory exists
+        mkdir -p "${outdir}"
+        # find the outfile
+        local outfile="${outdir}/${gps_start_time}_to_${gps_end_time}.${trend_extension}.${CHAN_TYPE}.dat"
     fi
+    echo -n "${outfile}"
 }
 
 # perform the nds_query and print output
@@ -182,14 +202,22 @@ dump_trend () {
     local gps_end_time="${2}"
     local channel_name="${3}"
     local trend_extension="${4}"
-    local outdir="${5}"
-    echo $gps_start_time >&2
-    echo $gps_end_time >&2
+    local outdir_pre="${5}"
     local delta_t=$((gps_end_time - gps_start_time))
-    echo $delta_t >&2
-    local outfile="${outdir}/${gps_start_time}_to_${gps_end_time}.${trend_extension}.${CHAN_TYPE}.dat"
+    local outfile="$(get_outfile "${gps_start_time}" "${gps_end_time}" \
+                    "${channel_name}" "${trend_extension}" "${outdir_pre}")"
+    # delete the outfile (will fail if file exists and -f not specified)
+    if ! "${print_timeseries_to_stdout}" && [ -e "${outfile}" ]; then
+        if "${force}"; then
+            rm -f "${outfile}"
+        else
+            echo "Error: must specify -f flag to overwrite existing files" >&2
+            usage
+            exit 1
+        fi
+    fi
     # next three lines add a descriptive header to the file
-    echo ${channel_name} > "${outfile}"
+    echo ${channel_name} >> "${outfile}"
     echo ${trend_extension} >> "${outfile}"
     printf 'GPS-TIME\tTREND-VALUE\n' >> "${outfile}"
     # this dumps the tabularized data
@@ -219,6 +247,37 @@ concatenate_time_segments () {
     "${stdin_from_pipe}" && cat -
 }
 
+# make sure the time segments provided are valid
+validate_time_segments () {
+    # must have at least one line
+    local lines=0
+    while read gps_start_time gps_end_time rest_of_line; do
+        lines=$((lines + 1))
+        # start must be before end
+        if [ ${gps_end_time} -le ${gps_start_time} ]; then
+            echo "Error: End time must be strictly greater than start." >&2
+            echo "    line number: ${lines}" >&2
+            echo "    line: ${gps_start_time} ${gps_end_time} ${rest_of_line}" >&2
+            usage
+            exit 1
+        fi
+        # there should only be two words
+        if ! [ -z "${rest_of_line}" ]; then
+            echo "Error: each time segment provided by pipe to STDIN must" >&2
+            echo "    be of the format '<start> <stop>' where both values" >&2
+            echo "    are integers representing GPS times." >&2
+        fi
+        echo "${gps_start_time} ${gps_end_time}"
+    done
+    # make sure we had at least one line
+    if [ $lines -eq 0 ]; then
+        echo "Error: must provide at least one pair of start/stop times," >&2
+        echo "    either using -s and -e flags or by piping to STDIN." >&2
+        usage
+        exit 1
+    fi
+}
+
 # round the start/stop times to the nearest integer multiples of 60 (round
 # start down and end up to be inclusive)
 round_time_segments () {
@@ -236,12 +295,12 @@ round_time_segments () {
 # aren't too long for nds to handle
 split_time_segments () {
     while read gps_start_time gps_end_time rest_of_line; do
-        next_epoch=$((gps_start_time / ${EPOCH_LENGTH}
-                      * ${EPOCH_LENGTH} + ${EPOCH_LENGTH}))
+        next_epoch=$((gps_start_time / ${MAX_TIME_INTERVAL}
+                      * ${MAX_TIME_INTERVAL} + ${MAX_TIME_INTERVAL}))
         split_segment="${gps_start_time} "
         while [ ${next_epoch} -lt ${gps_end_time} ]; do
             split_segment="${split_segment}${next_epoch}"$'\n'"${next_epoch} "
-            next_epoch=$((next_epoch + ${EPOCH_LENGTH}))
+            next_epoch=$((next_epoch + ${MAX_TIME_INTERVAL}))
         done
         split_segment="${split_segment}${gps_end_time}"
         echo "${split_segment}"
@@ -276,10 +335,6 @@ dump_time_segments () {
         fork_process_for_each_trend_extension \
             "${channel_name}" "${trend_extensions}"
     else
-        # get output directory
-        outdir="$(get_outdir "${outdir_pre}" "${channel_name}")"
-        # make sure output directory exists
-        mkdir -p "${outdir}"
         # read start/stop times and download data for each time segment
         while read gps_start_time gps_end_time rest_of_line; do
             if ! [ -z "${rest_of_line}" ]; then
@@ -291,7 +346,7 @@ dump_time_segments () {
                 exit 1
             fi
             dump_trend "${gps_start_time}" "${gps_end_time}" \
-                "${channel_name}" "${trend_extensions}" "${outdir}"
+                "${channel_name}" "${trend_extensions}" "${outdir_pre}"
         done
     fi
 }
@@ -305,8 +360,10 @@ start_time=""
 end_time=""
 channel_name=""
 trend_extensions=""
+force=false
+print_timeseries_to_stdout=false
 # DEFINE OPTION FLAGS BELOW
-while getopts ":s:e:t:p:c:fh" opt; do
+while getopts ":s:e:t:p:c:fTh" opt; do
     case ${opt} in
 # HANDLE OPTION FLAGS HERE
         s)  start_time="${OPTARG}";;
@@ -314,7 +371,8 @@ while getopts ":s:e:t:p:c:fh" opt; do
         c)  channel_name="${OPTARG}";;
         t)  trend_extensions="${OPTARG}";;
         p)  outdir_pre="${OPTARG}";;
-        f)  set +o noclobber;;
+        f)  set +o noclobber && force=true;;
+        T)  print_timeseries_to_stdout=true;;
         h)  usage; exit;;
         :)
             echo "Option -${OPTARG} requires an argument." >&2
@@ -330,16 +388,8 @@ while getopts ":s:e:t:p:c:fh" opt; do
 done
 shift $((OPTIND-1))
 # CONFIRM VALIDITY OF INPUT
-# start, end, channel_name, and trend_extensions are required
-if [ -z ${start_time:+x} ]; then
-    echo "Error: Must provide -s start_time." >&2
-    usage
-    exit 1
-elif [ -z ${end_time:+x} ]; then
-    echo "Error: Must provide -e end_time." >&2
-    usage
-    exit 1
-elif [ -z ${channel_name:+x} ]; then
+# channel_name and trend_extensions are required
+if [ -z ${channel_name:+x} ]; then
     echo "Error: Must provide -c channel_name" >&2
     usage
     exit 1
@@ -358,12 +408,6 @@ fi
 # get the gps times, in case the input was human-readable
 gps_start_time=$(lalapps_tconvert -t ${start_time})
 gps_end_time=$(lalapps_tconvert -t ${end_time})
-# start must be before end
-if [ ${gps_end_time} -le ${gps_start_time} ]; then
-    echo "Error: End time must be strictly greater than start time." >&2
-    usage
-    exit 1
-fi
 
 ##############################
 # MAIN BODY
@@ -371,6 +415,7 @@ fi
 
 # see if we have multiple trend extensions; if so, fork multiple processes
 concatenate_time_segments "${gps_start_time}" "${gps_end_time}" \
+    | validate_time_segments \
     | round_time_segments \
     | split_time_segments \
     | dump_time_segments "${gps_start_time}" "${gps_end_time}" \
