handle timeouts and restarts better, add colored logging

diff --git a/geco_trend_dump b/geco_trend_dump
--- a/geco_trend_dump
+++ b/geco_trend_dump
@@ -10,6 +10,20 @@ set -o noclobber # can be overridden with -f flag
 # set -o xtrace
 
 #------------------------------------------------------------------------------
+# CONSTANTS
+#------------------------------------------------------------------------------
+
+# DEFINE CONSTANTS
+MAX_TIME_INTERVAL=21600       # 21600 seconds is 6 hours
+SECONDS_PER_VAL=60            # Each value represents 60 seconds of data
+CHAN_TYPE='m-trend'           # Only use minute trends for now
+VALID_TREND_EXTENSIONS="mean min max n rms"
+NDS_SERVER='nds.ligo.caltech.edu'
+FULL_SCRIPT_PATH="$(readlink -f "${0}")" # use to recursively call this script
+SCRIPT_NAME="$(basename "${FULL_SCRIPT_PATH}")"
+LOGFILE=/dev/stderr           # by default, just log to STDERR
+
+#------------------------------------------------------------------------------
 # HELP MESSAGE
 #------------------------------------------------------------------------------
 usage() {
@@ -29,7 +43,7 @@ And the remaining lines are data, formatted as follows:
     - First column is the time column
     - Second column is the channel value column
 
-USAGE: geco_trend_dump [ -p output_directory ] -s start_time -e end_time -t trend_extensions -c channel_name
+USAGE: ${SCRIPT_NAME} [ -p output_directory ] -s start_time -e end_time -t trend_extensions -c channel_name
 
 ARGUMENTS:
 
@@ -73,10 +87,10 @@ OPTIONS:
                           rms and mean values.) This option is REQUIRED.
 
     -p output_directory   defaults to ~/. Timeseries text files will be saved
-                          to output_directory/geco_trend_dump.d/channel_name.
+                          to output_directory/${SCRIPT_NAME}.d/channel_name.
 
     -f                    force dump. Will overwrite the output of previous
-                          invocations of geco_trend_dump and will overwrite
+                          invocations of ${SCRIPT_NAME} and will overwrite
                           existing files without complaint.
 
     -T                    write dumped data to STDOUT instead of saving it to
@@ -94,9 +108,9 @@ EXAMPLES:
     Dump max, mean, and min trends from the first day of 2016 of the time
     difference between the aLIGO timing distribution system and the Hanford
     Main Storage Room Cs-III cesium clock 1PPS signals into separate
-    subdirectories of ~/timediffs/geco_trend_dump.d:
+    subdirectories of ~/timediffs/${SCRIPT_NAME}.d:
 
-        geco_trend_dump \\
+        ${SCRIPT_NAME} \\
                 -s 'Jan 1 2016 GMT' \\
                 -e 'Jan 2 2016 GMT' \\
                 -t max,mean,min \\
@@ -105,30 +119,18 @@ EXAMPLES:
 
     Get the same data for all operational segments at Hanford between Aug 1,
     2015 and May 1, 2016, and save it to the default directory,
-    ~/geco_trend_dump.d:
+    ~/${SCRIPT_NAME}.d:
 
         geco_get_operational_segments \\
                 -s 'Aug 1 2015' \\
                 -e 'May 1 2016' \\
                 -o H \\
-            | geco_trend_dump \\
+            | ${SCRIPT_NAME} \\
                 -t mean \\
                 -c H1:SYS-TIMING_C_MA_A_PORT_2_SLAVE_CFC_TIMEDIFF_1
 
 USAGE
 }
-
-#------------------------------------------------------------------------------
-# CONSTANTS
-#------------------------------------------------------------------------------
-
-# DEFINE CONSTANTS
-MAX_TIME_INTERVAL=21600       # 21600 seconds is 6 hours
-SECONDS_PER_VAL=60            # Each value represents 60 seconds of data
-CHAN_TYPE='m-trend'           # Only use minute trends for now
-VALID_TREND_EXTENSIONS="mean min max n rms"
-NDS_SERVER='nds.ligo.caltech.edu'
-LOGFILE=/dev/stderr           # by default, just log to STDERR
 
 #------------------------------------------------------------------------------
 # HELPER FUNCTIONS
@@ -137,7 +139,19 @@ LOGFILE=/dev/stderr           # by default, just log to STDERR
 # DEFINE HELPER FUNCTIONS
 
 log () {
-    printf '%s\n' "$(date +'%D %H:%M:%S:') $*" >> "$LOGFILE"
+    tput setaf 2
+    printf '%s' "$(date +'%D %H:%M:%S:')"
+    tput sgr0
+    printf '%s\n' " $*" >> "$LOGFILE"
+}
+
+die () {
+    log "$*"
+    exit 111
+}
+
+try () {
+    "$@" || die "Invalid: $*"
 }
 
 # get the path to the output directory based on channel name and path prefix
@@ -151,14 +165,14 @@ get_outfile () {
     if "${print_timeseries_to_stdout}"; then
         local outfile="/dev/stdout"
     else
-        # default output directory is ~/geco_trend_dump.d/channel_name;
-        # else is $outdir_pre/geco_trend_dump.d/channel_name
+        # default output directory is ~/${SCRIPT_NAME}.d/channel_name;
+        # else is $outdir_pre/${SCRIPT_NAME}.d/channel_name
         if [ "$outdir_pre" == "" ]; then
-            outdir="$HOME/geco_trend_dump.d/$(
+            outdir="$HOME/${SCRIPT_NAME}.d/$(
                 printf "%s" "${channel_name}" | tr ':' '_'
             )"
         else
-            outdir="${outdir_pre}/geco_trend_dump.d/$(
+            outdir="${outdir_pre}/${SCRIPT_NAME}.d/$(
                 printf "%s" "${channel_name}" | tr ':' '_'
             )"
         fi
@@ -181,9 +195,7 @@ run_nds_query () {
             -n "${NDS_SERVER}" \
             -s "${gps_start_time}" \
             -d "${delta_t}" \
-            -v "${channel_name}.${trend_extension},${CHAN_TYPE}" \
-        && log "nds_query finished." \
-        || ( [ $? -eq 124 ] && log "nds_query timed out." )
+            -v "${channel_name}.${trend_extension},${CHAN_TYPE}"
 }
 
 # reformat the output of an nds_query into a tabular format with time in the
@@ -213,24 +225,35 @@ dump_trend () {
     local outfile
     outfile="$(get_outfile "${gps_start_time}" "${gps_end_time}" \
                     "${channel_name}" "${trend_extension}" "${outdir_pre}")"
-    # delete the outfile (will fail if file exists and -f not specified)
-    if ! "${print_timeseries_to_stdout}" && [ -e "${outfile}" ]; then
-        if "${force}"; then
-            rm -f "${outfile}"
+    # temporary file. save dump to this tempfile, then rename it to the
+    # outfile once the dump is finished to make the dump atomic.
+    tmp="$(mktemp)"
+    # if the output file already exists, keep moving; otherwise, run query
+    if ! [ -e "${outfile}" ]; then
+        # next three lines add a descriptive header to the file
+        echo "${channel_name}" >> "${tmp}"
+        echo "${trend_extension}" >> "${tmp}"
+        printf 'GPS-TIME\tTREND-VALUE\n' >> "${tmp}"
+        # this dumps the tabularized data
+        run_nds_query "${gps_start_time}" "${delta_t}" \
+                "${channel_name}" "${trend_extension}" \
+            | tabularize_nds_query_result >> "${tmp}"
+        query_status="${PIPESTATUS[0]}"
+        # an exit code of 124 on the query indicates the request timed out
+        if [ "${query_status}" -eq 0 ]; then
+            mv "${tmp}" "${outfile}"
+            msg="nds_query succeeded: ${gps_start_time} ${delta_t} "
+            msg+="${channel_name} ${trend_extension}"
+            log "${msg}"
+        elif [ "${query_status}" -eq 124 ]; then
+            touch "${outfile}".timed_out
+            msg="nds_query timed out: ${gps_start_time} ${delta_t} "
+            msg+="${channel_name} ${trend_extension}"
+            log "${msg}"
         else
-            echo "Error: must specify -f flag to overwrite existing files" >&2
-            usage
-            exit 1
+            echo "Error: run_nds_query returned ${query_status}" >&2
         fi
     fi
-    # next three lines add a descriptive header to the file
-    echo "${channel_name}" >> "${outfile}"
-    echo "${trend_extension}" >> "${outfile}"
-    printf 'GPS-TIME\tTREND-VALUE\n' >> "${outfile}"
-    # this dumps the tabularized data
-    run_nds_query "${gps_start_time}" "${delta_t}" \
-            "${channel_name}" "${trend_extension}" \
-        | tabularize_nds_query_result >> "${outfile}"
 }
 
 # concatenate start/stop times specified using flags to the list of start/stop
@@ -322,14 +345,14 @@ fork_process_for_each_trend_extension () {
     local outdir_pre="${3}"
     # check: are we using -f flag to force overwrites?
     local _f
-    _f="$("${force}" && echo '-f' || true)"
+    _f="$(("${force}" && echo '-f') || true)"
     # make a folder for the named PIPES
     tmp_dir="$(mktemp -d)"
     # add comma to the front of the list to make name substitutions easier
     comma_trend_extensions=,"${trend_extensions}"
     for te in ${trend_extensions//,/ }; do
         mkfifo "${tmp_dir}/${te}"
-        geco_trend_dump \
+        "${FULL_SCRIPT_PATH}" \
                 -t "${te}" \
                 -c "${channel_name}" \
                 -p "${outdir_pre}" \
@@ -421,7 +444,7 @@ shift $((OPTIND-1))
 # CONFIRM VALIDITY OF INPUT
 # write to a log file in our output directory rather than STDERR
 mkdir -p "${outdir_pre}"
-LOGFILE="${outdir_pre}"/geco_trend_dump.log
+LOGFILE="${outdir_pre}"/"${SCRIPT_NAME}".log
 # channel_name and trend_extensions are required
 if [ -z ${channel_name:+x} ]; then
     echo "Error: Must provide -c channel_name" >&2
