add -R flag to read from dumped files

diff --git a/geco_dump b/geco_dump
--- a/geco_dump
+++ b/geco_dump
@@ -52,6 +52,14 @@ OPTIONS:
                           into other programs. This option can only be used
                           with a single channel specified.
 
+    -R                    dump a timeseries string from files previously
+                          output by geco_dump. Like the -T flag, but will read
+                          from text files previously generated by geco_dump,
+                          significantly increasing speed. If BOTH -R and -T
+                          are specified, geco_dump will try to read from
+                          previously generated text files before falling back
+                          to reading from GW frame files.
+
     -h                    shows this message.
 
 USAGE
@@ -90,6 +98,7 @@ dump () {
     # make it possible to print purely to a timeseries string. log messages
     # are printed only to stderr.
     print_timeseries_string=${5:-false}
+    read_from_dumped_files=${6:-false}
     # get data for each time
     current_time="${dump_start_time}"
     if ! [ -e "${outdir}" ]; then
@@ -100,9 +109,17 @@ dump () {
     while [ "${current_time}" -lt "${dump_end_time}" ]; do
         # create a descriptive path name where this should be saved
         outpath="${outdir}/${current_time}".dat
-        inpath=$(get_frame_file_path ${observatory_letter} ${current_time})
         # see if -T flag is activated, i.e. we are printing raw timeseries
-        if ${print_timeseries_string}; then
+        if ${read_from_dumped_files}; then
+            if [ -e "${outpath}" ]; then
+                # make sure the channel is correct
+                sed -n "2 {/${channel_name}/!q1};1,6d;s/^Data: //;s/ //g;p" ${outpath}
+            else
+                echo No data file found for ${current_time}, exiting. >&2
+                exit 1
+            fi
+        elif ${print_timeseries_string}; then
+            inpath=$(get_frame_file_path ${observatory_letter} ${current_time})
             if [ "${inpath}" == "" ]; then
                 echo No frame file found for ${current_time}, exiting. >&2
                 exit 1
@@ -114,16 +131,13 @@ dump () {
                     | tr -d ' '
             fi
         else
+            inpath=$(get_frame_file_path ${observatory_letter} ${current_time})
             # skip the file if it already exists
             if ! [ -e "${outpath}" ]; then
-                # get the file path for this time
+                # get the file path for this time; if missing, mark it so.
                 if [ "${inpath}" == "" ]; then
-                    # echo No frame file found for ${current_time}, skipping...
                     touch "${outpath}".missing
                 else
-                    # THE GW FRAME FILE PATH IS INCLUDED IN OUTPUT HEADER
-                    # echo Path to GW Frame File: ${inpath}
-                    # echo Dumping data to ${outpath}...
                     framecpp_dump_channel --channel "${channel_name}" \
                                           "${inpath}" > "${outpath}"
                     if [ -e "${outpath}".missing ]; then
@@ -160,9 +174,10 @@ outdir_pre=""
 start_time=""
 end_time=""
 check_dump_progress=false
+read_from_dumped_files=false
 print_timeseries_string=false
 unset channel_names
-while getopts ":p:s:e:c:l:PTh" opt; do
+while getopts ":p:s:e:c:l:PTRh" opt; do
     case ${opt} in
         p)  outdir_pre="${OPTARG}";;
         s)  start_time="${OPTARG}";;
@@ -175,6 +190,7 @@ while getopts ":p:s:e:c:l:PTh" opt; do
             ;;
         P)  check_dump_progress=true;;
         T)  print_timeseries_string=true;;
+        R)  read_from_dumped_files=true;;
         h)  usage && exit;;
         :)
             echo "Option -${OPTARG} requires an argument." >&2
@@ -212,12 +228,12 @@ elif [ "${#channel_names[*]}" == "0" ]; then
     echo "Error: Must provide at least one channel name with -c flag." >&2
     usage
     exit 1
-elif ${check_dump_progress} && ${print_timeseries_string}; then
-    echo "Error: Cannot specify both -P and -T flags at once." >&2
+elif ${print_timeseries_string} || ${read_from_dumped_files} && ${check_dump_progress}; then
+    echo "Error: Cannot specify -P and -T or -P and -R flags at once." >&2
     usage
     exit 1
-elif ${print_timeseries_string} && ! [ "${#channel_names[*]}" == "1" ]; then
-    echo "Error: Must specify exactly one channel name with -T flag." >&2
+elif ${print_timeseries_string} || ${read_from_dumped_files} && ! [ "${#channel_names[*]}" == "1" ]; then
+    echo "Error: Must specify exactly one channel name with -T or -R flag." >&2
     usage
     exit 1
 fi
@@ -262,7 +278,11 @@ else
         outdir="$(get_outdir "${outdir_pre}" "${channel_name}")"
         if ${print_timeseries_string}; then
             dump "${dump_start_time}" "${dump_end_time}" \
-                 "${outdir}" "${channel_name}" true \
+                 "${outdir}" "${channel_name}" true false \
+                | tr '\n' ','
+        elif ${read_from_dumped_files}; then
+            dump "${dump_start_time}" "${dump_end_time}" \
+                 "${outdir}" "${channel_name}" false true \
                 | tr '\n' ','
         else
             echo Forking for ${channel_name}
