add geco_dump with more uniform syntax

diff --git a/geco_dump_channel b/geco_dump_channel
--- a/geco_dump_channel
+++ b/geco_dump_channel
@@ -2,6 +2,7 @@
 
 # a script for dumping to text a timeseries for a given channel
 # over a given time range from the highest speed storage medium
+# Stefan Countryman 4/2/2016
 
 set -o errexit
 set -o nounset
@@ -11,27 +12,46 @@ set -o noclobber
 
 usage() {
     cat <<USAGE
-Usage: $0 [ -d output_directory ] start_time end_time channel_name
+USAGE: geco_dump_channel -s start_time -e end_time -c channel_name [ OPTIONS... ]
 
-where
+OPTIONS:
 
-    start_time         is in the form Sep 01 00:00:00 GMT 2015
-    end_time           is in the same form as start_time
-    channel_name       is the full channel name
+    -s start_time         is in the form Sep 01 00:00:00 GMT 2015. REQUIRED.
 
-and output_directory defaults to ~/channel_name.
+    -e end_time           is in the same form as start_time. REQUIRED.
 
-$0 -h shows this message.
+    -c channel_name       is the full channel name. REQUIRED.
+
+    -p output_directory   defaults to ~/. Timeseries text files will be saved
+                          to output_directory/channel_name.
+
+    -h help               shows this message.
+
 USAGE
 }
 
 # get options
-outdir=""
-while getopts ":d:h" opt; do
+outdir_pre=""
+start_time=""
+end_time=""
+channel_name=""
+while getopts ":p:s:e:c:h" opt; do
     case $opt in
-        d)
-            outdir="$OPTARG"
-            echo "-d was triggered, parameter: $OPTARG" >&2
+        p)
+            outdir_pre="$OPTARG"
+            # echo "-p was triggered, parameter: $OPTARG" >&2
+            ;;
+        s)
+            start_time="$OPTARG"
+            # echo "-s was triggered, parameter: $OPTARG" >&2
+            ;;
+        e)
+            end_time="$OPTARG"
+            # echo "-e was triggered, parameter: $OPTARG" >&2
+            ;;
+        c)
+            channel_name="$OPTARG"
+            # echo "-c was triggered, parameter: $OPTARG" >&2
             ;;
         h)
             usage
@@ -50,21 +70,33 @@ while getopts ":d:h" opt; do
 done
 shift $((OPTIND-1))
 
-# exit if too few arguments
-if ! [ "$#" == "3" ]; then
-    echo "Expected 3 arguments, got $# instead." >&2
+# there should be no non-flag arguments
+if ! [ "$#" == 0 ]; then
+    echo "Expected only flag arguments; got $# non-flag arguments." >&2
+    usage
+    exit 1
+elif [ "$start_time" == "" ]; then
+    echo "Error: Must provide start time with -s flag." >&2
+    usage
+    exit 1
+elif [ "$end_time" == "" ]; then
+    echo "Error: Must provide end time with -e flag." >&2
+    usage
+    exit 1
+elif [ "$channel_name" == "" ]; then
+    echo "Error: Must provide channel name with -c flag." >&2
     usage
     exit 1
 fi
 
-# get arguments
-start_time="$1"
-end_time="$2"
-channel_name="$3"
 # first letter of channel specifies observatory; needed by gw_data_find
 observatory_letter="$(echo $channel_name | head -c 1)"
-# default output directory is ~/channel_name
-[ "$outdir" == "" ] && outdir="$HOME/`printf "$channel_name" | tr ':' '_'`"
+# default output directory is ~/channel_name; else is outdir_pre/channel_name
+if [ "$outdir_pre" == "" ]; then
+    outdir="$HOME/$(printf "${channel_name}" | tr ':' '_')"
+else
+    outdir="${outdir_pre}/$(printf "${channel_name}" | tr ':' '_')"
+fi
 
 # translate times to gps
 gps_start_time=`lalapps_tconvert "$start_time"`
