add -T flag, add trailing args, verbosity--

diff --git a/geco_dump b/geco_dump
--- a/geco_dump
+++ b/geco_dump
@@ -12,7 +12,13 @@ set -o noclobber
 
 usage() {
     cat <<USAGE
-USAGE: geco_dump -s start_time -e end_time [ -l channel_list | -c channel_name [ ... ] ] [ OPTIONS ]
+USAGE: geco_dump [ OPTIONS ] -s start_time -e end_time [ -l channel_list | -c channel_name [ ... ] ] channel_names ...
+
+ARGUMENTS:
+
+    All arguments are interpreted as channel names. This makes it easy to use
+    a pipe and xargs to choose channel names. Other options must be set
+    using
 
 OPTIONS:
 
@@ -21,7 +27,11 @@ OPTIONS:
     -e end_time           is in the same form as start_time. REQUIRED.
 
     -c channel_name       is the full channel name. Can be used multiple times
-                          to specify multiple channels. This or -l is REQUIRED.
+			  to specify multiple channels. At least one channel is
+                          REQUIRED, either using the -c flag explicitly, listing
+                          channels as arguments, or specifying a predefined
+                          list of channels with the -l flag (all three can be
+                          combined).
 
     -l channel_list       is a keyword specifying one of the following preset
                           lists of channels:
@@ -34,9 +44,40 @@ OPTIONS:
     -P                    do not start a new dump, but check the progress of
                           an ongoing dump with the given parameters.
 
+    -T                    start a new dump, but instead of saving the output
+                          of framecpp_dump_channel to text files (complete
+                          with text headers), only output the concatenated
+                          timeseries as strings (with no header information
+			  or diagnostic messages). Useful for piping timeseries
+                          into other programs. This option can only be used
+                          with a single channel specified.
+
     -h                    shows this message.
 
 USAGE
+}
+
+# get the path to a frame file for observatory H or L for some time
+get_frame_file_path () {
+    observatory_letter=${1}
+    current_time=${2}
+    gw_data_find -o ${observatory_letter} \
+                 -t ${observatory_letter}1_R \
+                 -s ${current_time} \
+                 -e ${current_time} \
+                 -u file \
+        | sed 's/[^:^\/]*:\/\/[^\/]*//'
+}
+
+get_outdir () {
+    outdir_pre="${1}"
+    channel_name="${2}"
+    # default output directory is ~/channel_name; else is outdir_pre/channel_name
+    if [ "$outdir_pre" == "" ]; then
+        printf "$HOME/$(printf "${channel_name}" | tr ':' '_')"
+    else
+        printf "${outdir_pre}/$(printf "${channel_name}" | tr ':' '_')"
+    fi
 }
 
 # function for dumping channels (inspired by original geco_dump_channel)
@@ -46,6 +87,9 @@ dump () {
     dump_end_time="${2}"
     outdir="${3}"
     channel_name="${4}"
+    # make it possible to print purely to a timeseries string. log messages
+    # are printed only to stderr.
+    print_timeseries_string=${5:-false}
     # get data for each time
     current_time="${dump_start_time}"
     if ! [ -e "${outdir}" ]; then
@@ -55,24 +99,34 @@ dump () {
     observatory_letter="$(echo ${channel_name} | head -c 1)"
     while [ "${current_time}" -lt "${dump_end_time}" ]; do
         # create a descriptive path name where this should be saved
-    outpath="${outdir}/${current_time}".dat
-
-        # skip the file if it already exists
-        if ! [ -e "${outpath}" ]; then
-            # get the file path for this time
-            path=`gw_data_find -o ${observatory_letter} \
-                               -t ${observatory_letter}1_R \
-                               -s ${current_time} \
-                               -e ${current_time} \
-                               -u file \
-                | sed 's/[^:^\/]*:\/\/[^\/]*//'`
-            if [ "${path}" == "" ]; then
-                echo No frame file found for ${current_time}, skipping...
+        outpath="${outdir}/${current_time}".dat
+        inpath=$(get_frame_file_path ${observatory_letter} ${current_time})
+        # see if -T flag is activated, i.e. we are printing raw timeseries
+        if ${print_timeseries_string}; then
+            if [ "${inpath}" == "" ]; then
+                echo No frame file found for ${current_time}, exiting. >&2
+                exit 1
             else
-                echo Path: ${path}
-                echo Dumping data to ${outpath}...
                 framecpp_dump_channel --channel "${channel_name}" \
-                                      "${path}" > "${outpath}"
+                                      "${inpath}" \
+                    | sed '1,6d' \
+                    | sed 's/^Data: //' \
+                    | tr -d ' '
+            fi
+        else
+            # skip the file if it already exists
+            if ! [ -e "${outpath}" ]; then
+                # get the file path for this time
+                if [ "${inpath}" == "" ]; then
+                    # echo No frame file found for ${current_time}, skipping...
+                    touch "${outpath}".skipped
+                else
+                    # THE GW FRAME FILE PATH IS INCLUDED IN OUTPUT HEADER
+                    # echo Path to GW Frame File: ${inpath}
+                    # echo Dumping data to ${outpath}...
+                    framecpp_dump_channel --channel "${channel_name}" \
+                                          "${inpath}" > "${outpath}"
+                fi
             fi
         fi
 
@@ -102,8 +156,9 @@ outdir_pre=""
 start_time=""
 end_time=""
 check_dump_progress=false
+print_timeseries_string=false
 unset channel_names
-while getopts ":p:s:e:c:l:Ph" opt; do
+while getopts ":p:s:e:c:l:PTh" opt; do
     case ${opt} in
         p)  outdir_pre="${OPTARG}";;
         s)  start_time="${OPTARG}";;
@@ -115,6 +170,7 @@ while getopts ":p:s:e:c:l:Ph" opt; do
             esac
             ;;
         P)  check_dump_progress=true;;
+        T)  print_timeseries_string=true;;
         h)  usage && exit;;
         :)
             echo "Option -${OPTARG} requires an argument." >&2
@@ -129,6 +185,12 @@ while getopts ":p:s:e:c:l:Ph" opt; do
 done
 shift $((OPTIND-1))
 
+# any trailing arguments are interpreted as channels
+while (( "$#" )); do
+    channel_names+=("${1}")
+    shift
+done
+
 # there should be no non-flag arguments
 if ! [ "$#" == 0 ]; then
     echo "Expected only flag arguments; got $# non-flag arguments." >&2
@@ -142,8 +204,16 @@ elif [ "${end_time}" == "" ]; then
     echo "Error: Must provide end time with -e flag." >&2
     usage
     exit 1
-elif ! [ "${channel_names}" ]; then
+elif [ "${#channel_names[*]}" == "0" ]; then
     echo "Error: Must provide at least one channel name with -c flag." >&2
+    usage
+    exit 1
+elif ${check_dump_progress} && ${print_timeseries_string}; then
+    echo "Error: Cannot specify both -P and -T flags at once." >&2
+    usage
+    exit 1
+elif ${print_timeseries_string} && ! [ "${#channel_names[*]}" == "1" ]; then
+    echo "Error: Must specify exactly one channel name with -T flag." >&2
     usage
     exit 1
 fi
@@ -166,9 +236,9 @@ if ${check_dump_progress}; then
         date
         printf 'SIZE MODIFIED         CHANNEL\n'
         for channel_name in ${channel_names[*]}; do
-            dir="$(printf "${channel_name}" | tr ':' '_')"
-            usg=$(du -h --time --max-depth=0 "${dir}")
-            cnt=$(ls "${dir}" | wc -l)
+            outdir="$(get_outdir "${outdir_pre}" "${channel_name}")"
+            usg=$(du -h --time --max-depth=0 "${outdir}")
+            cnt=$(ls "${outdir}" | wc -l)
             pct=$(dc -e "${cnt} 100*${num_frame_files}/p")
             echo ${usg} ${cnt}/${num_frame_files} \(${pct}\%\)
         done
@@ -185,16 +255,17 @@ else
     dump_end_time=$(dc -e "${gps_end_time} 64/64*64+p")
     # fork a process for each channel dump and print output to a log file
     for channel_name in ${channel_names[*]}; do
-        # default output directory is ~/channel_name; else is outdir_pre/channel_name
-        if [ "$outdir_pre" == "" ]; then
-            outdir="$HOME/$(printf "${channel_name}" | tr ':' '_')"
+        outdir="$(get_outdir "${outdir_pre}" "${channel_name}")"
+        if ${print_timeseries_string}; then
+            dump "${dump_start_time}" "${dump_end_time}" \
+                 "${outdir}" "${channel_name}" true \
+                | tr '\n' ','
         else
-            outdir="${outdir_pre}/$(printf "${channel_name}" | tr ':' '_')"
+            echo Forking for ${channel_name}
+            logfile="${outdir}.log"
+            dump "${dump_start_time}" "${dump_end_time}" \
+                 "${outdir}" "${channel_name}" \
+                >> "${logfile}" &
         fi
-        echo Forking for ${channel_name}
-        logfile="$(printf "${channel_name}" | tr ':' '_').log"
-        dump "${dump_start_time}" "${dump_end_time}" \
-             "${outdir}" "${channel_name}" \
-            >> "${logfile}" &
     done
 fi
